### ISSUE TITLE
Center text entry fields, add second paragraph of text

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#37]
This screenshot shows the desired layout:

![img_1963](https://cloud.githubusercontent.com/assets/1497818/8420598/ad4dcf38-1e89-11e5-94e2-d239f532ee34.JPG)

**Comment by kfogel** [comment]
The text of the second paragraph (i.e., the new one on the right) is:

The American Red Cross and its partners have launched an initiative that aims to reduce deaths and injuries caused by home fires by 25% in five years with the Home Fire Preparedness Campaign. The Red Cross is asking every household in America to join us in taking two simple steps that can save lives: checking or installing smoke alarms and practicing fire drills at home.
