### ISSUE TITLE
Add admin area to Red Cross site.

### ISSUE THREAD

**Issue by trystant** [OpenTechStrategies/smoke-alarm-portal#44]
The administrative area will add the ability to have a distinct area that only admins can access, as well as an area that grants a simple reporting feature for requests that have been entered. 

My initial desire was to integrate a version of [Drywall](https://github.com/trystant/drywall) user and admin system for Node that uses [Sequelize](http://sequelize.readthedocs.org/en/latest/) to connect to Postgres, which we are using now.

I forked a fork that had been started, but was configured to use ES6 ("Harmony").

I believe that it will take me 6 - 8 hours to:

* Replace the ES6 compatible code with current JS code.
* Remove unneeded code in order to implement the admin and user functionality.
* Integrate this into the current application
* Provide documentation for the reasons behind implementing this as well as installation

@kfogel, @cecilia-donnelly - Please let me know your thoughts. Thanks.

**Comment by kfogel** [comment]
Thanks, Mark.

(Question: should we try to upgrade to ES6?  How far are we from it now?  It is The Future, after all.)

More importantly:

How much calendar time is the 6-8 hours?  I.e., what's the completion date? :-)

Why is the removal of unneeded code necessary "in order to implement the admin and user functionality"?

**Comment by trystant** [comment]
The general code has been added to the repo under the drywall_integration branch. If you start the app in this branch, youSuccessive commits show the pieces of drywall (heh) that have been added to the repository. I've been stuck on replicating the drywall user administration process shown [here](https://github.com/jedireza/drywall#setup) in a Sequelize migration, a process that has turned out to have some challenges associated with it. For example; doing sequential SQL inserts becomes a challenge in a Promise based library. The migration code that I have currently has the Promise/callback pyramid hell, which is shown below:

````
 db.AdminGroup.create({ name: 'Root' }).then(function(adminGroup) {
      db.Admin.create({ name: 'Root Admin'}).then(function(admin) {
        admin.setAdminGroup(adminGroup);
        admin.save();
        db.User.create({ username: 'root', isActive: 'yes', email: 'mark@grandkru.com'}).then(function(user) {
          user.setAdmin(admin);
          user.save();
        });
      });
    });

Even this code doesn't completely create the users needed to go to the next stage of setup and use the "Forgot Password" functionality to create an initial user (which in and of itself could use improvement).

Once this piece is in place, the remaining steps for this would include:
1. Verifying login/password functionality on the integrated instances
2. Verifying grunt tasks to generate uglified css work for both the app and the admin

I've spent six hours on this so far. I think that there may be more work ahead due to:
* User role functions in the mongoose version not being fully implemented in the sequelize version

My next commit will connect app functionality so that the admin pages come up, even if there's not a user as of yet.

**Comment by cecilia-donnelly** [comment]
@trystant thanks for the update.  I tried to run the code on this branch and ran into some errors, even after copying config.example.js to config.js  (I didn't make any other changes to the file, which could be the problem here):

In the console, I get: 

```
Unhandled rejection SequelizeDatabaseError: type "json" does not exist
    at Query.formatError (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
    at null.<anonymous> (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
    at emit (events.js:95:17)
    at Query.handleError (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
Unhandled rejection SequelizeDatabaseError: type "json" does not exist
    at Query.formatError (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
    at null.<anonymous> (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
    at emit (events.js:95:17)
    at Query.handleError (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/home/cdonnelly/OTS/smoke-alarm-portal/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
TypeError: Object #<IncomingMessage> has no method 'post'
```

In the browser Drywall comes up with a Server Error and a similar message, also referencing `TypeError: Object #<IncomingMessage> has no method 'post'`.  I'm not sure what changes (if any) I should make to config.example.js, or whether that is the source of this error.

**Comment by trystant** [comment]
@cecilia-donnelly Thanks for this update. I'm confirming the behavior on my end. Is this in response to the `npm start` command?

**Comment by trystant** [comment]
While creating the SQL script to this, I've realized that I need to create another relation (that did not exist before). Between that the issue I ran into when trying to remove User attributes and the relation that didn't exist before, I'm digging in a bit deeper to Sequelize relations.

**Comment by kfogel** [comment]
Is that a "I've run into something but it looks simple to solve" or a "I've run into something and I don't yet know how deep this rabbit hole goes so I can't really estimate it" ?  Not a facetious question -- answer number 2 is okay, I just want to understand which situation we're dealing with.

**Comment by trystant** [comment]
The admin area has been merged back into master as of 24d9ee6. I believe that this satisfies the functionality, but I do need to check and see what documentation I need to update.

**Comment by trystant** [comment]
Good morning.

With commit 779c923, the requests can be viewed at the index and individual level.

As discussed in the commit, there needs to be a tweak for filtering, but the rest of the functionality is in place.

@cecilia-donnelly, @kfogel let me know your thoughts.

**Comment by cecilia-donnelly** [comment]
@trystant hey, thanks for the comment!  I don't see the commit you're referring to -- are you sure you pushed?

**Comment by trystant** [comment]
Sorry, check for this commit: 63fe8d5b7527b0ef4462802978e6a40125dd2fc1

````
 1 commit 63fe8d5b7527b0ef4462802978e6a40125dd2fc1
      2 Author: Mark Nyon <mark@grandkru.com>
      3 Date:   Tue Jul 21 14:18:51 2015 -0400
      4
      5     Additional code for Admin of Requests
      6
      7     This includes the HTML/JS/CSS for the Request admin section as well as
      8     additional routes for managing the Request resources.
      9
     10 public/views/admin/requests/details.js
     11 public/views/admin/requests/details.less
     12 public/views/admin/requests/details.min.css
     13 public/views/admin/requests/details.min.js
     14 public/views/admin/requests/details.min.js.map
     15 public/views/admin/requests/index.js
     16 public/views/admin/requests/index.less
     17 public/views/admin/requests/index.min.css
     18 public/views/admin/requests/index.min.js
     19 public/views/admin/requests/index.min.js.map
     20 routes.js
     21 views/admin/requests/details.jade
     22 views/admin/requests/index.jade
     23 views/admin/requests/index.js
````

**Comment by cecilia-donnelly** [comment]
@trystant thanks!  I see the commit and I'll check it out in my copy.

**Comment by cecilia-donnelly** [comment]
Hey, great!  Reporting exists!  Some initial feedback on this for @trystant and @kfogel:

- There's no link on the homepage that points to the admin area, and once in the admin area, there's no link to go to the requests report.  This might be obvious, but we should have those things
- The "edit" buttons next to each request don't work.  They fail with this error:
```
TypeError: Cannot read property 'Request' of undefined
at getRecord (/home/cdonnelly/OTS/smoke-alarm-portal/views/admin/requests/index.js:52:26)
at /home/cdonnelly/OTS/smoke-alarm-portal/node_modules/async/lib/async.js:567:21
```
I don't think we actually need an "edit" button on the requests, but we definitely shouldn't have a broken one.
- The requests don't yet have "date/time submitted" as a column, which is definitely something users will want.
- What does the "Add New" button in the top right do?
- Searching or sorting and then pressing enter hangs.


Much of this is probably expected, @trystant.  I'm not sure what was intended to work after this commit, based only on your commit message.  We should definitely split some of these out into other issues/enhancements, too.  Let me know what the expected behavior is, and we'll talk about how we want to enhance this feature.

Thanks for your time on this!

**Comment by kfogel** [comment]
Thanks!

I don't think we want a link from the home page to the admin area.  No user cares about the admin area or even knows it exists.  The Red Cross admins will just know the admin URL (because we'll give it to them, and it should be "/admin" on the site, which I haven't checked if it is yet but that's easy to change anyway).

**Comment by kfogel** [comment]
Haven't seen the rest yet, will look soon!  Just responding quickly to the above comments above.  Also, right: no need for an edit button.  The way requests enter the system is through the front page.  We are *not* building a request management system in this initial contract.  That's a much bigger deal and we've talked about it for Phase 2, but we can't possibly do it in the Phase 1 budget and shouldn't try.  The requirements elicitation process for that alone is almost equivalent to the effort of just building Phase 1.

**Comment by kfogel** [comment]
Update to an above comment:

The current URL path, "`/admin/requests/`", is fine.  When I get a chance, I'll file some separate tickets about further changes, but right now we know at least these:

* [ ] The "Edit" button next to each Request can go away, since we won't be editing them.
* [ ] We need to have some kind of authorization protection to keep random people from creating new admin-privileged users just by knowing the magic URL.  Thoughts on a good way to do this?

**Comment by kfogel** [comment]
Closing this issue -- it's done.  The rest of the work is in other tickets now.
