### ISSUE TITLE
Combine phone and email into one field.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#47]
Since phone numbers and email addresses are easily distinguishable, we can use one field to receive both, thus doing away with the complicated requirement/error logic that results from having two separate fields from which a minimum of one is required to be filled in valid data.  (Combining them into one field will require some customization to the validation code, of course.)

Note that this affects issue #46 but does not obviate it.

**Comment by nttaylor** [comment]
@kfogel was convinced to let these fields remain separate (but still on the same row) in the questionable name of doing-what-people-are-already-used-to vs doing-what-people-should-be-doing-if-only-they-knew-how-much-better-their-lives-could-be. For better or worse, this issue is now closed following 3f62923

**Comment by kfogel** [comment]
Fools.  Bureaucratic fools.  They don't know what they've got there.
